package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: versiongen <server-pyproject.toml> <output-go-file>")
		os.Exit(2)
	}
	version, err := pyprojectVersion(os.Args[1])
	if err != nil {
		fmt.Fprintf(os.Stderr, "versiongen: %v\n", err)
		os.Exit(1)
	}
	output := fmt.Sprintf(`// Code generated by cmd/versiongen; DO NOT EDIT.

package cli

const serverVersion = %q
`, version)
	if err := os.WriteFile(os.Args[2], []byte(output), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "versiongen: %v\n", err)
		os.Exit(1)
	}
}

func pyprojectVersion(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	inProject := false
	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		if strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]") {
			inProject = trimmed == "[project]"
			continue
		}
		if !inProject || !strings.HasPrefix(trimmed, "version") {
			continue
		}
		key, value, ok := strings.Cut(trimmed, "=")
		if !ok || strings.TrimSpace(key) != "version" {
			continue
		}
		version := strings.Trim(strings.TrimSpace(value), `"`)
		if version == "" || version == strings.TrimSpace(value) {
			return "", fmt.Errorf("%s has unsupported project.version syntax", filepath.Clean(path))
		}
		return version, nil
	}
	return "", fmt.Errorf("%s does not define [project] version", filepath.Clean(path))
}
