[pytest]
addopts = --import-mode=importlib
testpaths =
    server/tests
    plugins/smtp/tests
    plugins/imap/tests
    examples/plugins/echo/tests
pythonpath =
    server/src
    plugins/smtp/src
    plugins/imap/src
